In [32]:
import cv2
import glob

import os  
import csv
import numpy as np
import random
import dlib
from skimage import io


In [33]:
#Define 7 types of emotions, corresponding to the 7 types in CK+ dataset
emotions = ["anger", "contempt", "disgust", "fear", "happy", "sadness", "surprise"]
rootpath1 = "/Users/scott/Documents/2017Fall/UROP1100/Emotion"

#Extract label information from CK+ dataset folder
def listdir(path):  
    list_dir = os.listdir(path)
    return list_dir
label = []
label_file = []
list_dir = listdir(rootpath1)
a = 0
list_dir.sort()
for i in range(1,len(list_dir)):
    if list_dir[i]!=".DS_Store":
        path_1 = rootpath1 +"/"+list_dir[i]
        list_dir_1 = listdir(path_1)
        #print(list_dir_1)
        list_dir_1.sort
        for j in range(0,len(list_dir_1)):
            if list_dir_1[j]!=".DS_Store":
                path_2 = path_1+"/"+list_dir_1[j]
                list_dir_2 = listdir(path_2)
                list_dir_2.sort
                if(list_dir_2!=[]):
                    #print(list_dir_2)
                    a = a+1
                    label_file.append(list_dir_2[0])
                    with open(path_2+"/"+list_dir_2[0]) as f:
                        content = f.readlines()
                        #print(content[0].rstrip('.0000000e+00\n'))
                        label.append(int(content[0].rstrip('.0000000e+00\n')))
print(label_file)
print(len(label))

['S005_001_00000011_emotion.txt', 'S010_006_00000015_emotion.txt', 'S010_004_00000019_emotion.txt', 'S010_002_00000014_emotion.txt', 'S011_001_00000016_emotion.txt', 'S011_006_00000013_emotion.txt', 'S011_003_00000014_emotion.txt', 'S011_004_00000021_emotion.txt', 'S011_005_00000020_emotion.txt', 'S011_002_00000022_emotion.txt', 'S014_001_00000029_emotion.txt', 'S014_003_00000030_emotion.txt', 'S014_005_00000017_emotion.txt', 'S014_002_00000016_emotion.txt', 'S022_001_00000030_emotion.txt', 'S022_006_00000017_emotion.txt', 'S022_005_00000032_emotion.txt', 'S026_001_00000015_emotion.txt', 'S026_006_00000013_emotion.txt', 'S026_003_00000015_emotion.txt', 'S026_002_00000016_emotion.txt', 'S028_001_00000024_emotion.txt', 'S029_001_00000019_emotion.txt', 'S032_001_00000022_emotion.txt', 'S032_006_00000016_emotion.txt', 'S032_003_00000017_emotion.txt', 'S032_004_00000014_emotion.txt', 'S032_005_00000016_emotion.txt', 'S034_001_00000029_emotion.txt', 'S034_003_00000027_emotion.txt', 'S034_005

In [34]:
#Extract Landmark information from CK+ dataset folder
f1 = []
f2 = []
for i in range(len(label_file)):
    temp = label_file[i].rstrip('_emotion.txt')
    print(temp)
    f2.append(temp)
    temp = temp.split('_')
    f1.append(temp)
    print(f1[i])
rootpath2 = "/Users/scott/Documents/2017Fall/UROP1100/Landmarks"
X1 = []
X2 = []
landmark_file = []
landmark_file.append([])
landmark_file.append([])
add = 0
for i in range(len(label_file)):
    path = rootpath2 +"/" + f1[i][0] + "/" + f1[i][1]
    landmark_file[0].append(path+"/"+f1[i][0]+"_"+f1[i][1]+"_00000001_landmarks.txt")
    landmark_file[1].append(path+"/"+f2[i]+ "_landmarks.txt")
    with open(landmark_file[0][i]) as f:
        contents = f.readlines()
        tmpData = []
        for j in range(len(contents)):
            content = contents[j].rstrip('\n')
            content = content.split(' ')
            for k in range(len(content)):
                if(content[k]!='' and content[k]!='\n'):
                     tmpData.append(float(content[k]))
        X1.append(tmpData)
    with open(landmark_file[1][i]) as f:
        contents = f.readlines()
        tmpData = []
        for j in range(len(contents)):
            content = contents[j].rstrip('\n')
            content = content.split(' ')
            for k in range(len(content)):
                if(content[k]!='' and content[k]!='\n'):
                    tmpData.append(float(content[k]))
        X2.append(tmpData)


S005_001_00000011
['S005', '001', '00000011']
S010_006_00000015
['S010', '006', '00000015']
S010_004_00000019
['S010', '004', '00000019']
S010_002_00000014
['S010', '002', '00000014']
S011_001_00000016
['S011', '001', '00000016']
S011_006_00000013
['S011', '006', '00000013']
S011_003_00000014
['S011', '003', '00000014']
S011_004_00000021
['S011', '004', '00000021']
S011_005_00000020
['S011', '005', '00000020']
S011_002_00000022
['S011', '002', '00000022']
S014_001_00000029
['S014', '001', '00000029']
S014_003_00000030
['S014', '003', '00000030']
S014_005_00000017
['S014', '005', '00000017']
S014_002_00000016
['S014', '002', '00000016']
S022_001_00000030
['S022', '001', '00000030']
S022_006_00000017
['S022', '006', '00000017']
S022_005_00000032
['S022', '005', '00000032']
S026_001_00000015
['S026', '001', '00000015']
S026_006_00000013
['S026', '006', '00000013']
S026_003_00000015
['S026', '003', '00000015']
S026_002_00000016
['S026', '002', '00000016']
S028_001_00000024
['S028', '001', 

['S147', '002', '00000013']
S148_002_00000015
['S148', '002', '00000015']
S149_002_00000013
['S149', '002', '00000013']
S151_002_00000029
['S151', '002', '00000029']
S154_002_00000013
['S154', '002', '00000013']
S155_002_00000012
['S155', '002', '00000012']
S156_002_00000021
['S156', '002', '00000021']
S157_002_00000011
['S157', '002', '00000011']
S158_002_00000011
['S158', '002', '00000011']
S160_006_00000010
['S160', '006', '00000010']
S501_001_00000067
['S501', '001', '00000067']
S501_006_00000041
['S501', '006', '00000041']
S501_004_00000056
['S501', '004', '00000056']
S502_001_00000016
['S502', '001', '00000016']
S502_004_00000052
['S502', '004', '00000052']
S502_002_00000009
['S502', '002', '00000009']
S503_001_00000071
['S503', '001', '00000071']
S503_006_00000020
['S503', '006', '00000020']
S503_002_00000008
['S503', '002', '00000008']
S504_001_00000022
['S504', '001', '00000022']
S504_006_00000018
['S504', '006', '00000018']
S504_004_00000015
['S504', '004', '00000015']
S504_0

In [35]:
#Preprocess the data
X1 = np.array(X1,dtype = np.float)
X2 = np.array(X2,dtype = np.float)
X_1 = np.zeros([327,68,2])
X_2 = np.zeros([327,68,2])
for i in range(327):
    for j in range(68):
        for k in range(2):
            X_1[i,j,k] = X1[i,j*2+k]
            X_2[i,j,k] = X2[i,j*2+k]
label = np.array(label,dtype=np.int )
X1 = X_1
X2 = X_2

In [36]:
#Preprecess the data to the correct dimension
X = np.sqrt(np.sum(np.square(X1-X2),axis = 2))
X = np.sum((X1-X2),axis=2)
print(X.shape)

(327, 68)


In [37]:
from sklearn import preprocessing
X_norm = preprocessing.scale(X)
print(X_norm[0])

[-0.14509032  0.00447955  0.19483366  0.31416686  0.41200046  0.44807115
  0.52532626  0.49427881  0.54424947  0.86390981  1.23888142  1.55555329
  1.26755988  0.04146969  0.26477966  0.07593798 -0.11539135  0.03340437
 -0.36945796 -0.5025369  -0.56707942 -0.66169938 -1.19220606 -0.50997751
 -0.38778047 -0.15546858 -0.32258721 -0.88499945 -0.77626405 -0.74950242
 -0.42641643  0.54706175  0.53603371  0.35525927  0.34584723  0.52624933
 -0.23962544 -0.04424023 -0.08049142  0.43698422  0.53748445  0.400385
 -0.58321648 -1.20765103 -0.99257555 -0.70103711  0.03465651  0.13034964
  0.0747477   0.51150533  0.1555838   0.11856335  0.35780605  0.73175177
  0.81035336  0.78378088  0.70744449  0.67120106  0.59560947  0.3294256
 -0.11206383 -0.35459584  0.01580787  0.5455914   0.96940528  0.96071386
  0.85032439  0.49201996]


In [38]:
#Perform PCA on the data
from sklearn.decomposition import PCA
pca = PCA(n_components='mle')
pca.fit(X_norm)
print pca.explained_variance_ratio_
print pca.explained_variance_
X_new = pca.transform(X_norm)
print(X_new.shape)
print(X_new)

[  4.97877240e-01   3.13319509e-01   4.57869500e-02   3.61475694e-02
   2.25700984e-02   1.49284159e-02   9.59194993e-03   6.79901272e-03
   6.10064548e-03   4.99316144e-03   4.29120278e-03   3.90159765e-03
   3.61454551e-03   3.46172955e-03   3.07036434e-03   2.51841251e-03
   2.19197491e-03   1.76332414e-03   1.55116610e-03   1.41342284e-03
   1.33210380e-03   1.24169639e-03   1.09804539e-03   1.00185096e-03
   8.66540131e-04   8.47461926e-04   7.44277240e-04   6.53435673e-04
   6.20186645e-04   5.37453516e-04   4.97916901e-04   4.48308229e-04
   3.84299919e-04   3.73748004e-04   3.46643433e-04   3.11600448e-04
   2.54229507e-04   2.37991717e-04   2.18177617e-04   1.99116623e-04
   1.84488031e-04   1.75457934e-04   1.41956472e-04   1.32884112e-04
   1.11886552e-04   1.09613139e-04   9.88238145e-05   9.53081279e-05
   9.00748319e-05   8.23214367e-05   7.87048514e-05   7.11240089e-05
   6.71516383e-05   5.43815723e-05   5.38837430e-05   4.62157250e-05
   4.09780286e-05   3.63484004e-05

In [39]:
from sklearn import svm
from sklearn import cross_validation
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import confusion_matrix

In [40]:
#Using liniear SVM and show the corresponding confusion matrix
clf = svm.SVC()
clf.fit(X_new[0:240], label[0:240])
result = clf.predict(X_new[240:])
num_correct=(np.sum(result==label[240:]))
accuracy = float(num_correct)/result.shape[0]
print('Got %d / %d correct => accuracy: %f' % (num_correct,result.shape[0],accuracy))
conf_mat = confusion_matrix(label[240:],result)
print(conf_mat)

Got 61 / 87 correct => accuracy: 0.701149
[[12  0  0  0  0  0  1]
 [ 4  0  2  0  0 12  0]
 [ 1  0  7  0  0  0  0]
 [ 0  0  0  5  1  0  3]
 [ 0  0  0  0 14  0  0]
 [ 1  0  0  0  0 11  0]
 [ 0  0  0  0  0  1 12]]


In [41]:
#Cross Validation resulte from linear SVM
clf = svm.SVC(kernel='linear', C=1)
scores = cross_validation.cross_val_score(clf, X_new, label, cv=5)
print(scores)
print(np.mean(scores))

[ 0.94029851  0.88059701  0.88059701  0.875       0.91935484]
0.899169475205


In [42]:
#Cross Valiation result Using Two layer neural network
clf = MLPClassifier(solver='lbfgs', alpha=1e-5,
                    hidden_layer_sizes=(20, 7), random_state=1)
scores = cross_validation.cross_val_score(clf, X_new, label, cv=5)
print(scores)
print(np.mean(scores))

[ 0.94029851  0.79104478  0.88059701  0.875       0.88709677]
0.87480741454


In [43]:
#Confusion matrix
from sklearn.model_selection import cross_val_predict
from sklearn.metrics import confusion_matrix
y_pred = cross_val_predict(clf,X_new,label,cv=5)
conf_mat = confusion_matrix(label,y_pred)
print(conf_mat)

[[36  2  7  0  0  0  0]
 [ 1 12  2  1  0  1  1]
 [10  0 49  0  0  0  0]
 [ 1  0  0 17  3  2  2]
 [ 0  0  1  1 67  0  0]
 [ 1  2  0  0  0 25  0]
 [ 0  1  0  1  0  1 80]]


In [44]:
#On Yale dataset
import csv
import numpy as np
import dlib
from skimage import io
import matplotlib.pyplot as plt
import cv2
import os  
import random

In [45]:
predictor_path = "/Users/scott/Downloads/shape_predictor_68_face_landmarks.dat"
cascade_path = ["/usr/local/Cellar/opencv/3.3.1_1/share/OpenCV/haarcascades/haarcascade_frontalface_default.xml",
                "/usr/local/Cellar/opencv/3.3.1_1/share/OpenCV/haarcascades/haarcascade_frontalface_alt.xml",
                "/usr/local/Cellar/opencv/3.3.1_1/share/OpenCV/haarcascades/haarcascade_frontalface_alt2.xml",
               "/usr/local/Cellar/opencv/3.3.1_1/share/OpenCV/haarcascades/haarcascade_frontalface_alt_tree.xml"]
emotions_yale = ["happy","sad","surprised"]
features = np.zeros([100,68,2])
labels = np.zeros([100,1])
faceCascade = cv2.CascadeClassifier(cascade_path[1])
predictor = dlib.shape_predictor(predictor_path)
Y_X = []
Y_label = []
for i in range(15):
    #image = io.imread("/Users/scott/Downloads/cohn-kanade-images/S005/001/S005_001_00000001.png")#np.array(pixels,dtype=np.uint8)
    folder_path = "/Users/scott/Documents/YALE/unpadded/"
    if(i<10):
        image_path = folder_path + "subject0"+str(i+1)
    else:
        image_path = folder_path + "subject" + str(i+1)
    normal_image = cv2.imread(image_path+".normal.pgm",-1)
    print(normal_image.shape)
    faces = faceCascade.detectMultiScale(  
           normal_image,  
           scaleFactor=1.01,  
           minNeighbors=3,  
           minSize=(20, 20),  
           flags=cv2.CASCADE_SCALE_IMAGE  
        ) 
        #print("Found {0} faces!".format(len(faces))) 
    for(x, y, w, h) in faces:
        cv2.rectangle(normal_image, (x, y), (x + w, y + h), (0, 255, 0), 2)
    dlib_rect = dlib.rectangle(int(x), int(y), int(x + w), int(y + h)) 
    shape = predictor(normal_image, dlib_rect)
    allshape = shape.parts()
    temp_normal = []
    for j in range(3):
        if(j==0):
            image = cv2.imread(image_path+".happy.pgm")
        elif(j==1):
            image = cv2.imread(image_path+".happy.pgm")
        faces = faceCascade.detectMultiScale(  
           image,  
           scaleFactor=1.1,  
           minNeighbors=3,  
           minSize=(20, 20),  
           flags=cv2.CASCADE_SCALE_IMAGE  
        ) 
        #print("Found {0} faces!".format(len(faces))) 
        for (x, y, w, h) in faces:
            cv2.rectangle(image, (x, y), (x + w, y + h), (0, 255, 0), 2)
        dlib_rect = dlib.rectangle(int(x), int(y), int(x + w), int(y + h)) 
        shape = predictor(image, dlib_rect)
        allshape = shape.parts()

RuntimeError: Unable to open /Users/scott/Downloads/shape_predictor_68_face_landmarks.dat